---
- name: Copy nocodb folder
  copy:
    src: ./docker/nocodb
    dest: ~/docker
    mode: 0755

- name: Shut down service
  shell: |
    cd ~/docker/nocodb
    docker compose down

- name: Start nocodb
  shell: |
    cd ~/docker/nocodb
    export NETWORK={{network}}
    export LOG_MAX_SIZE={{log_max_size}}
    export LOG_MAX_FILE={{log_max_file}}
    docker compose up -d
