---
- name: Deploy airflow service

  hosts: lottery1

  vars_files:
    - vars/common.yml
    - vars/timezone.yml

  tasks:
    - import_tasks: tasks/airflow/start.yml
    # - import_tasks: tasks/common/prune.yml
