version: "3.8"
# This is an example setup with an Nginx reverse proxy.
# If you already have an Nginx reverse proxy running,
# then allow the docker-compose.yml to reference an external network that the reverse proxy container is on
# (in lieu of the frontend network in this file) and have the NocoDB container connect to it.
services: 
  nocobase: 
    container_name: nocobase
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - APP_KEY=nocobase-vgroup-2024
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=nocobase.vgroup.com.vn
      - LETSENCRYPT_HOST=nocobase.vgroup.com.vn
      - LETSENCRYPT_EMAIL=anvn@vgroup.vn
    image: nocobase/nocobase:main
    networks:
      - default
    restart: always
    ports: 
      - 80
    volumes:
      - ./storage:/app/nocobase/storage
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true