version: '3.8'

services:
  baserow:
    container_name: baserow
    restart: always
    image: baserow/baserow:1.22.1
    environment:
      - BASEROW_PUBLIC_URL=https://baserow.vgroup.com.vn
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=baserow.vgroup.com.vn
      - LETSENCRYPT_HOST=baserow.vgroup.com.vn
      - LETSENCRYPT_EMAIL=anvn@vgroup.vn
      - DATABASE_HOST=${POSTGRES_HOST}
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://${REDIS_HOST}:6379
    ports:
      - 80
    volumes:
      - ./baserow_data:/baserow/data
      - ./baserow_media:/baserow/media
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}
    networks:
      - default

networks:
  default:
    name: nginx_proxy
    external: true