---
- name: Copy nocobase folder
  copy:
    src: ./docker/nocobase
    dest: ~/docker
    mode: 0755

- name: Shut down service
  shell: |
    cd ~/docker/nocobase
    docker compose down

- name: Start nocobase
  shell: |
    cd ~/docker/nocobase
    export NETWORK={{network}}
    export LOG_MAX_SIZE={{log_max_size}}
    export LOG_MAX_FILE={{log_max_file}}
    docker compose up -d
