---
- name: Copy budibase folder
  copy:
    src: ./docker/budibase
    dest: ~/docker
    mode: 0755

- name: Shut down service
  shell: |
    cd ~/docker/budibase
    docker compose down

- name: Start budibase
  shell: |
    cd ~/docker/budibase
    export TZ={{tz}}
    export NETWORK={{network}}
    export LOG_MAX_SIZE={{log_max_size}}
    export LOG_MAX_FILE={{log_max_file}}
    docker compose up -d
